// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: nobi.proto

package nobi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_nobi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type AddUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserResponse) Reset() {
	*x = AddUserResponse{}
	mi := &file_nobi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserResponse) ProtoMessage() {}

func (x *AddUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserResponse.ProtoReflect.Descriptor instead.
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{1}
}

func (x *AddUserResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateTotalBalanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentBalance float64                `protobuf:"fixed64,1,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateTotalBalanceRequest) Reset() {
	*x = UpdateTotalBalanceRequest{}
	mi := &file_nobi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTotalBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTotalBalanceRequest) ProtoMessage() {}

func (x *UpdateTotalBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTotalBalanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateTotalBalanceRequest) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTotalBalanceRequest) GetCurrentBalance() float64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

type UpdateTotalBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NabAmount     float64                `protobuf:"fixed64,1,opt,name=nab_amount,json=nabAmount,proto3" json:"nab_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTotalBalanceResponse) Reset() {
	*x = UpdateTotalBalanceResponse{}
	mi := &file_nobi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTotalBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTotalBalanceResponse) ProtoMessage() {}

func (x *UpdateTotalBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTotalBalanceResponse.ProtoReflect.Descriptor instead.
func (*UpdateTotalBalanceResponse) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTotalBalanceResponse) GetNabAmount() float64 {
	if x != nil {
		return x.NabAmount
	}
	return 0
}

type ListNABRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNABRequest) Reset() {
	*x = ListNABRequest{}
	mi := &file_nobi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNABRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNABRequest) ProtoMessage() {}

func (x *ListNABRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNABRequest.ProtoReflect.Descriptor instead.
func (*ListNABRequest) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{4}
}

type NABEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nab           float64                `protobuf:"fixed64,1,opt,name=nab,proto3" json:"nab,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NABEntry) Reset() {
	*x = NABEntry{}
	mi := &file_nobi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NABEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NABEntry) ProtoMessage() {}

func (x *NABEntry) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NABEntry.ProtoReflect.Descriptor instead.
func (*NABEntry) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{5}
}

func (x *NABEntry) GetNab() float64 {
	if x != nil {
		return x.Nab
	}
	return 0
}

func (x *NABEntry) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ListNABResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nabs          []*NABEntry            `protobuf:"bytes,1,rep,name=nabs,proto3" json:"nabs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNABResponse) Reset() {
	*x = ListNABResponse{}
	mi := &file_nobi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNABResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNABResponse) ProtoMessage() {}

func (x *ListNABResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNABResponse.ProtoReflect.Descriptor instead.
func (*ListNABResponse) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{6}
}

func (x *ListNABResponse) GetNabs() []*NABEntry {
	if x != nil {
		return x.Nabs
	}
	return nil
}

type TopUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountRupiah  float64                `protobuf:"fixed64,2,opt,name=amount_rupiah,json=amountRupiah,proto3" json:"amount_rupiah,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUpRequest) Reset() {
	*x = TopUpRequest{}
	mi := &file_nobi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUpRequest) ProtoMessage() {}

func (x *TopUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUpRequest.ProtoReflect.Descriptor instead.
func (*TopUpRequest) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{7}
}

func (x *TopUpRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TopUpRequest) GetAmountRupiah() float64 {
	if x != nil {
		return x.AmountRupiah
	}
	return 0
}

type TopUpResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NilaiUnitHasilTopup float64                `protobuf:"fixed64,1,opt,name=nilai_unit_hasil_topup,json=nilaiUnitHasilTopup,proto3" json:"nilai_unit_hasil_topup,omitempty"`
	NilaiUnitTotal      float64                `protobuf:"fixed64,2,opt,name=nilai_unit_total,json=nilaiUnitTotal,proto3" json:"nilai_unit_total,omitempty"`
	SaldoRupiahTotal    float64                `protobuf:"fixed64,3,opt,name=saldo_rupiah_total,json=saldoRupiahTotal,proto3" json:"saldo_rupiah_total,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TopUpResponse) Reset() {
	*x = TopUpResponse{}
	mi := &file_nobi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUpResponse) ProtoMessage() {}

func (x *TopUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUpResponse.ProtoReflect.Descriptor instead.
func (*TopUpResponse) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{8}
}

func (x *TopUpResponse) GetNilaiUnitHasilTopup() float64 {
	if x != nil {
		return x.NilaiUnitHasilTopup
	}
	return 0
}

func (x *TopUpResponse) GetNilaiUnitTotal() float64 {
	if x != nil {
		return x.NilaiUnitTotal
	}
	return 0
}

func (x *TopUpResponse) GetSaldoRupiahTotal() float64 {
	if x != nil {
		return x.SaldoRupiahTotal
	}
	return 0
}

type WithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountRupiah  float64                `protobuf:"fixed64,2,opt,name=amount_rupiah,json=amountRupiah,proto3" json:"amount_rupiah,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	mi := &file_nobi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRequest.ProtoReflect.Descriptor instead.
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{9}
}

func (x *WithdrawRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WithdrawRequest) GetAmountRupiah() float64 {
	if x != nil {
		return x.AmountRupiah
	}
	return 0
}

type WithdrawResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	NilaiUnitSetelahWithdraw float64                `protobuf:"fixed64,1,opt,name=nilai_unit_setelah_withdraw,json=nilaiUnitSetelahWithdraw,proto3" json:"nilai_unit_setelah_withdraw,omitempty"`
	NilaiUnitTotal           float64                `protobuf:"fixed64,2,opt,name=nilai_unit_total,json=nilaiUnitTotal,proto3" json:"nilai_unit_total,omitempty"`
	SaldoRupiahTotal         float64                `protobuf:"fixed64,3,opt,name=saldo_rupiah_total,json=saldoRupiahTotal,proto3" json:"saldo_rupiah_total,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *WithdrawResponse) Reset() {
	*x = WithdrawResponse{}
	mi := &file_nobi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResponse) ProtoMessage() {}

func (x *WithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawResponse.ProtoReflect.Descriptor instead.
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{10}
}

func (x *WithdrawResponse) GetNilaiUnitSetelahWithdraw() float64 {
	if x != nil {
		return x.NilaiUnitSetelahWithdraw
	}
	return 0
}

func (x *WithdrawResponse) GetNilaiUnitTotal() float64 {
	if x != nil {
		return x.NilaiUnitTotal
	}
	return 0
}

func (x *WithdrawResponse) GetSaldoRupiahTotal() float64 {
	if x != nil {
		return x.SaldoRupiahTotal
	}
	return 0
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *int32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Page          *int32                 `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_nobi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{11}
}

func (x *ListMembersRequest) GetUserId() int32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *ListMembersRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListMembersRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type MemberEntry struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	UserId                  int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalUnitPerUid         float64                `protobuf:"fixed64,2,opt,name=total_unit_per_uid,json=totalUnitPerUid,proto3" json:"total_unit_per_uid,omitempty"`
	TotalAmountrupiahPerUid float64                `protobuf:"fixed64,3,opt,name=total_amountrupiah_per_uid,json=totalAmountrupiahPerUid,proto3" json:"total_amountrupiah_per_uid,omitempty"`
	CurrentNab              float64                `protobuf:"fixed64,4,opt,name=current_nab,json=currentNab,proto3" json:"current_nab,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MemberEntry) Reset() {
	*x = MemberEntry{}
	mi := &file_nobi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberEntry) ProtoMessage() {}

func (x *MemberEntry) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberEntry.ProtoReflect.Descriptor instead.
func (*MemberEntry) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{12}
}

func (x *MemberEntry) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberEntry) GetTotalUnitPerUid() float64 {
	if x != nil {
		return x.TotalUnitPerUid
	}
	return 0
}

func (x *MemberEntry) GetTotalAmountrupiahPerUid() float64 {
	if x != nil {
		return x.TotalAmountrupiahPerUid
	}
	return 0
}

func (x *MemberEntry) GetCurrentNab() float64 {
	if x != nil {
		return x.CurrentNab
	}
	return 0
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*MemberEntry         `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_nobi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nobi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_nobi_proto_rawDescGZIP(), []int{13}
}

func (x *ListMembersResponse) GetMembers() []*MemberEntry {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_nobi_proto protoreflect.FileDescriptor

const file_nobi_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"nobi.proto\x12\x04nobi\"@\n" +
	"\x0eAddUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"*\n" +
	"\x0fAddUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"D\n" +
	"\x19UpdateTotalBalanceRequest\x12'\n" +
	"\x0fcurrent_balance\x18\x01 \x01(\x01R\x0ecurrentBalance\";\n" +
	"\x1aUpdateTotalBalanceResponse\x12\x1d\n" +
	"\n" +
	"nab_amount\x18\x01 \x01(\x01R\tnabAmount\"\x10\n" +
	"\x0eListNABRequest\"0\n" +
	"\bNABEntry\x12\x10\n" +
	"\x03nab\x18\x01 \x01(\x01R\x03nab\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"5\n" +
	"\x0fListNABResponse\x12\"\n" +
	"\x04nabs\x18\x01 \x03(\v2\x0e.nobi.NABEntryR\x04nabs\"L\n" +
	"\fTopUpRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12#\n" +
	"\ramount_rupiah\x18\x02 \x01(\x01R\famountRupiah\"\x9c\x01\n" +
	"\rTopUpResponse\x123\n" +
	"\x16nilai_unit_hasil_topup\x18\x01 \x01(\x01R\x13nilaiUnitHasilTopup\x12(\n" +
	"\x10nilai_unit_total\x18\x02 \x01(\x01R\x0enilaiUnitTotal\x12,\n" +
	"\x12saldo_rupiah_total\x18\x03 \x01(\x01R\x10saldoRupiahTotal\"O\n" +
	"\x0fWithdrawRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12#\n" +
	"\ramount_rupiah\x18\x02 \x01(\x01R\famountRupiah\"\xa9\x01\n" +
	"\x10WithdrawResponse\x12=\n" +
	"\x1bnilai_unit_setelah_withdraw\x18\x01 \x01(\x01R\x18nilaiUnitSetelahWithdraw\x12(\n" +
	"\x10nilai_unit_total\x18\x02 \x01(\x01R\x0enilaiUnitTotal\x12,\n" +
	"\x12saldo_rupiah_total\x18\x03 \x01(\x01R\x10saldoRupiahTotal\"\x85\x01\n" +
	"\x12ListMembersRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x05H\x00R\x06userId\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x02 \x01(\x05H\x01R\x04page\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x02R\x05limit\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\a\n" +
	"\x05_pageB\b\n" +
	"\x06_limit\"\xb1\x01\n" +
	"\vMemberEntry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12+\n" +
	"\x12total_unit_per_uid\x18\x02 \x01(\x01R\x0ftotalUnitPerUid\x12;\n" +
	"\x1atotal_amountrupiah_per_uid\x18\x03 \x01(\x01R\x17totalAmountrupiahPerUid\x12\x1f\n" +
	"\vcurrent_nab\x18\x04 \x01(\x01R\n" +
	"currentNab\"B\n" +
	"\x13ListMembersResponse\x12+\n" +
	"\amembers\x18\x01 \x03(\v2\x11.nobi.MemberEntryR\amembers2\x91\x03\n" +
	"\x15NobiInvestmentService\x126\n" +
	"\aAddUser\x12\x14.nobi.AddUserRequest\x1a\x15.nobi.AddUserResponse\x12W\n" +
	"\x12UpdateTotalBalance\x12\x1f.nobi.UpdateTotalBalanceRequest\x1a .nobi.UpdateTotalBalanceResponse\x126\n" +
	"\aListNAB\x12\x14.nobi.ListNABRequest\x1a\x15.nobi.ListNABResponse\x120\n" +
	"\x05TopUp\x12\x12.nobi.TopUpRequest\x1a\x13.nobi.TopUpResponse\x129\n" +
	"\bWithdraw\x12\x15.nobi.WithdrawRequest\x1a\x16.nobi.WithdrawResponse\x12B\n" +
	"\vListMembers\x12\x18.nobi.ListMembersRequest\x1a\x19.nobi.ListMembersResponseB\rZ\vpkg/pb/nobib\x06proto3"

var (
	file_nobi_proto_rawDescOnce sync.Once
	file_nobi_proto_rawDescData []byte
)

func file_nobi_proto_rawDescGZIP() []byte {
	file_nobi_proto_rawDescOnce.Do(func() {
		file_nobi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nobi_proto_rawDesc), len(file_nobi_proto_rawDesc)))
	})
	return file_nobi_proto_rawDescData
}

var file_nobi_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_nobi_proto_goTypes = []any{
	(*AddUserRequest)(nil),             // 0: nobi.AddUserRequest
	(*AddUserResponse)(nil),            // 1: nobi.AddUserResponse
	(*UpdateTotalBalanceRequest)(nil),  // 2: nobi.UpdateTotalBalanceRequest
	(*UpdateTotalBalanceResponse)(nil), // 3: nobi.UpdateTotalBalanceResponse
	(*ListNABRequest)(nil),             // 4: nobi.ListNABRequest
	(*NABEntry)(nil),                   // 5: nobi.NABEntry
	(*ListNABResponse)(nil),            // 6: nobi.ListNABResponse
	(*TopUpRequest)(nil),               // 7: nobi.TopUpRequest
	(*TopUpResponse)(nil),              // 8: nobi.TopUpResponse
	(*WithdrawRequest)(nil),            // 9: nobi.WithdrawRequest
	(*WithdrawResponse)(nil),           // 10: nobi.WithdrawResponse
	(*ListMembersRequest)(nil),         // 11: nobi.ListMembersRequest
	(*MemberEntry)(nil),                // 12: nobi.MemberEntry
	(*ListMembersResponse)(nil),        // 13: nobi.ListMembersResponse
}
var file_nobi_proto_depIdxs = []int32{
	5,  // 0: nobi.ListNABResponse.nabs:type_name -> nobi.NABEntry
	12, // 1: nobi.ListMembersResponse.members:type_name -> nobi.MemberEntry
	0,  // 2: nobi.NobiInvestmentService.AddUser:input_type -> nobi.AddUserRequest
	2,  // 3: nobi.NobiInvestmentService.UpdateTotalBalance:input_type -> nobi.UpdateTotalBalanceRequest
	4,  // 4: nobi.NobiInvestmentService.ListNAB:input_type -> nobi.ListNABRequest
	7,  // 5: nobi.NobiInvestmentService.TopUp:input_type -> nobi.TopUpRequest
	9,  // 6: nobi.NobiInvestmentService.Withdraw:input_type -> nobi.WithdrawRequest
	11, // 7: nobi.NobiInvestmentService.ListMembers:input_type -> nobi.ListMembersRequest
	1,  // 8: nobi.NobiInvestmentService.AddUser:output_type -> nobi.AddUserResponse
	3,  // 9: nobi.NobiInvestmentService.UpdateTotalBalance:output_type -> nobi.UpdateTotalBalanceResponse
	6,  // 10: nobi.NobiInvestmentService.ListNAB:output_type -> nobi.ListNABResponse
	8,  // 11: nobi.NobiInvestmentService.TopUp:output_type -> nobi.TopUpResponse
	10, // 12: nobi.NobiInvestmentService.Withdraw:output_type -> nobi.WithdrawResponse
	13, // 13: nobi.NobiInvestmentService.ListMembers:output_type -> nobi.ListMembersResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_nobi_proto_init() }
func file_nobi_proto_init() {
	if File_nobi_proto != nil {
		return
	}
	file_nobi_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nobi_proto_rawDesc), len(file_nobi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nobi_proto_goTypes,
		DependencyIndexes: file_nobi_proto_depIdxs,
		MessageInfos:      file_nobi_proto_msgTypes,
	}.Build()
	File_nobi_proto = out.File
	file_nobi_proto_goTypes = nil
	file_nobi_proto_depIdxs = nil
}
